import useThemeColors from '@hooks/useThemeMode';
import HomeHeader from '@screens/Home/Components/HomeHeader';
import React, { memo, useEffect, useState } from 'react';
import {
  Alert,
  Keyboard,
  KeyboardAvoidingView,
  Platform,
  StyleSheet,
  TouchableWithoutFeedback,
  View,
} from 'react-native';
import { LatLng } from 'react-native-maps';
import { useSharedValue, withTiming } from 'react-native-reanimated';

import useLocationNotification from '../../Hooks/useLocationNotification';
import { Notification } from '../../Types/Interface';
import LocationDetailsCard from './Components/LocationDetailsCard';
import LocationMapView from './Components/LocationMapView';
import LocationSearchBar from './Components/LocationSearchBar';

const LocationDetails = () => {
  const colors = useThemeColors();
  const { scheduleLocationNotification } = useLocationNotification();
  const [selectedLocation, setSelectedLocation] = useState<LatLng | null>(null);
  const [title, setTitle] = useState('');
  const [message, setMessage] = useState('');
  const [search, setSearch] = useState('');
  const [isSearchFocused, setIsSearchFocused] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const cardAnim = useSharedValue(0);

  useEffect(() => {
    cardAnim.value = withTiming(isSearchFocused ? 0 : 1, { duration: 300 });
  }, [isSearchFocused]);

  const handleLocationSelect = (coordinate: LatLng) => {
    setSelectedLocation(coordinate);
  };

  const validateAndSubmit = async () => {
    if (!selectedLocation) {
      Alert.alert('Validation', 'Please select a location on the map.');
      return;
    }
    if (!title.trim()) {
      Alert.alert('Validation', 'Please enter a title.');
      return;
    }
    if (!message.trim()) {
      Alert.alert('Validation', 'Please enter a message.');
      return;
    }

    setIsLoading(true);
    try {
      const notificationData: Notification = {
        id: '', // This will be generated by the hook
        type: 'location',
        message: message.trim(),
        date: new Date(),
        subject: title.trim(),
        toContact: [],
        toMail: [],
        attachments: [],
        scheduleFrequency: null,
        days: [],
        memo: [],
        telegramUsername: '',
        latitude: selectedLocation.latitude,
        longitude: selectedLocation.longitude,
        radius: 100, // 100 meters default
        locationName: search || '',
      };

      const notificationId = await scheduleLocationNotification(notificationData);
      if (notificationId) {
        Alert.alert('Success', 'Location-based reminder scheduled successfully!');
        // Reset form
        setTitle('');
        setMessage('');
        setSelectedLocation(null);
      }
    } catch (error: any) {
      Alert.alert('Error', String(error?.message || error));
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={{ flex: 1 }}
      behavior={Platform.OS === 'ios' ? 'padding' : 'padding'}
    >
      <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
        <View style={[styles.container, { backgroundColor: colors.background }]}>
          <HomeHeader
            title={'Location'}
            titleAlignment="center"
            leftIconType="back"
            showThemeSwitch={false}
          />
          <LocationMapView
            onLocationSelect={handleLocationSelect}
            selectedLocation={selectedLocation}
          >
            <LocationSearchBar
              value={search}
              onChangeText={setSearch}
              onFocus={() => setIsSearchFocused(true)}
              onBlur={() => setIsSearchFocused(false)}
            />
          </LocationMapView>
          <LocationDetailsCard
            title={title}
            setTitle={setTitle}
            message={message}
            setMessage={setMessage}
            onCreate={validateAndSubmit}
            isLoading={isLoading}
          />
        </View>
      </TouchableWithoutFeedback>
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default memo(LocationDetails);
