import BottomSheet, { BottomSheetView } from '@gorhom/bottom-sheet';
import useThemeColors from '@Hooks/useThemeMode';
import HomeHeader from '@Screens/Home/Components/HomeHeader';
import React, { memo, useRef, useState } from 'react';
import { Alert, StyleSheet, View } from 'react-native';

import useLocationNotification from '@Hooks/useLocationNotification';
import { GeoLatLng, Notification } from '@Types/Interface';
import LocationDetailsCard from './Components/LocationDetailsCard';
import LocationMapView from './Components/LocationMapView';
import LocationSearchBar, { NominatimResult } from './Components/LocationSearchBar';

const LocationDetails = () => {
  const colors = useThemeColors();
  const { scheduleLocationNotification } = useLocationNotification();

  const [title, setTitle] = useState('');
  const [message, setMessage] = useState('');
  const [search, setSearch] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [selectedLocation, setSelectedLocation] = useState<GeoLatLng | null>(null);

  const bottomSheetRef = useRef<BottomSheet>(null);

  const handleLocationSelect = (coordinate: GeoLatLng) => {
    setSelectedLocation(coordinate);

    bottomSheetRef?.current?.snapToIndex(1);
  };

  const handleSearchResultSelect = (result: NominatimResult) => {
    setSearch(result.display_name);
    setSelectedLocation({ latitude: parseFloat(result.lat), longitude: parseFloat(result.lon) });
  };

  const validateAndSubmit = async () => {
    if (!selectedLocation) {
      Alert.alert('Validation', 'Please select a location on the map.');
      return;
    }
    if (!title.trim()) {
      Alert.alert('Validation', 'Please enter a title.');
      return;
    }
    if (!message.trim()) {
      Alert.alert('Validation', 'Please enter a message.');
      return;
    }

    setIsLoading(true);
    try {
      const notificationData: Notification = {
        id: '', // This will be generated by the hook
        type: 'location',
        message: message.trim(),
        date: new Date(),
        subject: title.trim(),
        toContact: [],
        toMail: [],
        attachments: [],
        scheduleFrequency: null,
        days: [],
        memo: [],
        telegramUsername: '',
        latitude: selectedLocation.latitude,
        longitude: selectedLocation.longitude,
        radius: 100, // 100 meters default
        locationName: search || '',
      };

      const notificationId = await scheduleLocationNotification(notificationData);
      if (notificationId) {
        Alert.alert('Success', 'Location-based reminder scheduled successfully!');
        // Reset form
        setTitle('');
        setMessage('');
        setSelectedLocation(null);
      }
    } catch (error: any) {
      Alert.alert('Error', String(error?.message || error));
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <HomeHeader
        title={'Location'}
        titleAlignment="center"
        leftIconType="back"
        showThemeSwitch={false}
      />
      <LocationMapView onLocationSelect={handleLocationSelect} selectedLocation={selectedLocation}>
        <LocationSearchBar
          value={search}
          onChangeText={setSearch}
          onResultSelect={handleSearchResultSelect}
        />
        <BottomSheet
          handleStyle={{
            borderBottomWidth: 0.5,
            borderColor: colors.reminderCardBackground,
            backgroundColor: colors.reminderCardBackground,
          }}
          handleIndicatorStyle={{ backgroundColor: colors.white }}
          style={{
            borderBottomWidth: 0,
            zIndex: 999999999,
            backgroundColor: colors.reminderCardBackground,
          }}
          snapPoints={['5%', '33%']}
          ref={bottomSheetRef}
          keyboardBlurBehavior="restore"
          keyboardBehavior="interactive"
          android_keyboardInputMode="adjustPan"
        >
          <BottomSheetView
            style={[styles.contentContainer, { backgroundColor: colors.reminderCardBackground }]}
          >
            <LocationDetailsCard
              title={title}
              setTitle={setTitle}
              message={message}
              setMessage={setMessage}
              onCreate={validateAndSubmit}
              isLoading={isLoading}
            />
          </BottomSheetView>
        </BottomSheet>
      </LocationMapView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1 },
  contentContainer: { flex: 1 },
});

export default memo(LocationDetails);
