#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint
if [ $? -ne 0 ]; then
  echo "\n❌ Lint errors found. Please fix them before pushing."
  exit 1
fi

yarn tsc --noEmit
if [ $? -ne 0 ]; then
  echo "\n❌ TypeScript errors found. Please fix them before pushing."
  exit 1
fi 